### ISSUE TITLE
Fehler "Unbekannte Repräsentation" und "Unbekanntes Merkmal" mit eigener Repräsentation und Merkmal in eigenem Zauber

### ISSUE THREAD

**Issue by Fenir** [MarkusBauer/helden-software-loader#15]
Ich habe in meinem YAML-File folgende Daten definiert:

```
repräsentationen:
  - name: Hochelfisch
    abkürzung: Hoc
    ritualkenntnis: true

sonderfertigkeiten:
  - name: Erweckung
    kosten: 100
    kategorie: Merkmalskenntnis

zauber:
    - name: "Ensiferi Klingentanz"
      kategorie: "C"
      merkmale:
        - Erweckung
        - "Telekinese"
      probe: KL/IN/GE
      settings:
        - Aventurien
      verbreitung:
        Hoc: 4
        Mag: 2
        Srl: 2
      spezialisierungen:
        - Zauberdauer
        - "Erzwingen"
        - Wie von Gesterhand
        - Imaginärer Freund
 ```

Ich erhalte beim Start zunächst die Fehlermeldung, dass `Hoc` unbekannt sei. Wenn ich das bei `verbreitung` auskommentiere, wirft als nächstes das Merkmal Erweckung einen Fehler. Muss ich das anders konfigurieren oder liegt es an der Ladereihenfolge?

**Comment by MarkusBauer** [comment]
Hi,
das sollte mit der [neuen Version 1.9.0](https://github.com/MarkusBauer/helden-software-loader/releases/tag/v1.9.0) jetzt machbar sein.

Neu hinzugekommen sind eigene Merkmale. Die werden nicht als Sonderfertigkeit definiert, sondern so:
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/MarkusBauer/helden-software-loader/refs/heads/master/erweiterungen.schema.json

merkmale:
  - name: Erweckung
    abkürzung: Erw
    stufe: 1  # =100AP
```

Danach kann das Merkmal in Zaubern benutzt werden, und die SF Merkmalskenntnis wird automatisch mit erzeugt (und verbilligt auch korrekt). 

Das Problem mit "`Hoc` unbekannt" liegt tatsächlich an der Reihenfolge. Der umgekehrte Weg (Zauber bei Repräsentation eintragen) müsste auch mit alten Versionen funktionieren. 
Ich hab den Code jetzt etwas umstrukturiert, sodass deine Variante auch funktionieren sollte.

VG Markus
